### ISSUE TITLE
clash wth https://forge.puppet.com/puppetlabs/concat

### ISSUE THREAD

**Issue by FayeG** [theforeman/puppet-concat#16]
Hi,

Looks like you both define: Puppet::Type.newtype(:concat_fragment)

0 codo:3rd_party# grep -r concat_fragment concat concat_native/ | grep Type.newtype
concat/lib/puppet/type/concat_fragment.rb:Puppet::Type.newtype(:concat_fragment) do
concat_native/lib/puppet/type/concat_fragment.rb:Puppet::Type.newtype(:concat_fragment) do
0 codo:3rd_party#

Which then causes a clash as the two types have different parameters.

**Comment by mmoll** [comment]
The README clearly says: `This module is deprecated in favour of puppetlabs-concat 2.0.0 or higher.`

**Comment by FayeG** [comment]
true but it was pulled in by theforeman-dhcp as a dep.

**Comment by mmoll** [comment]
Version 1.6.0 of theforeman/dhcp (released Mar 5th 2015) was the last release requiring concat_native. We switched to puppetlabs-concat with 2.0.0.
